
### Format JSON
POST https://api.webutils.xyz/format_json/
Content-Type: application/json

{
    "indent": 4,
    "input_string": "{\"name\": \"John\", \"age\": 30}",
    "sort_keys": true
}

### Query in clause
POST https://api.webutils.xyz/query_in_clause_generator/
Content-Type: application/json

{
    "strings": "\na\nb\nc\nd\ne\n"
}
